#include "MainWindow.h"
#include "VideoPlayer.h"
#include "Timeline.h"
#include "ExportDialog.h"
#include "UndoManager.h"
#include "OverlayDialogs.h"
#include "VideoEffectDialogs.h"
#include "EffectPlugin.h"
#include "ColorGradingPanel.h"
#include "LumetriScopes.h"
#include <QDockWidget>
#include "GLPreview.h"
#include "ProxyManager.h"
#include "ProxyProgressDialog.h"
#include "ProxyManagementDialog.h"
#include <QApplication>
#include <QMessageBox>
#include <QVBoxLayout>
#include <QProgressDialog>
#include <QShortcut>
#include <QInputDialog>
#include <QCloseEvent>
#include <QFile>
#include <QFileInfo>
#include <QTimer>
#include <QPointer>
#include <QUrl>
#include <QDebug>
#include <QActionGroup>
#include <QSignalBlocker>
#include <QStackedWidget>
#include <QLineEdit>
#include <QSpinBox>
#include <QDoubleSpinBox>
#include <QCheckBox>
#include <QComboBox>
#include <QScrollArea>
#include <QFrame>
#include <QInputDialog>
#include <QStandardPaths>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QDir>
#include <cmath>
#include "AudioMeterWidget.h"
#include "GradientStopBar.h"
#include <QPushButton>
#include <QDialog>
#include <QDialogButtonBox>
#include <QHBoxLayout>
#include <QSettings>
#include <QSlider>
#include <QColorDialog>
#include <QFormLayout>
#include <QLabel>
#include <QStandardItemModel>
